import {
  AlertOctagon,
  ArrowUpRight,
  CheckCircle2,
  CircleDashed,
  Clock,
  Copy,
  FileQuestion,
  HelpCircle,
  Loader2,
  SearchX,
  Sparkles,
  XCircle,
  Ban,
  Eye,
  Archive,
} from "lucide-react";
import type { Category, FindingStatus, RunStatus } from "@/api/types";
import { Badge, type BadgeTone } from "@/components/ui/badge";
import { Tip } from "@/components/ui/menus";
import { cn } from "@/lib/utils";

/* ---------------- AIBadge ---------------- */
export function AIBadge({ className, label = "AI", title }: { className?: string; label?: string; title?: string }) {
  return (
    <Badge tone="ai" className={cn("gap-0.5", className)} title={title ?? "Generated by the AI agent"}>
      <Sparkles aria-hidden />
      <span>{label}</span>
    </Badge>
  );
}

/* ---------------- CategoryBadge ---------------- */
export const CATEGORY_META: Record<Category, { label: string; tone: BadgeTone; icon: typeof Copy; help: string }> = {
  duplicate: {
    label: "Duplicate",
    tone: "attn",
    icon: Copy,
    help: "The same payment appears more than once in the bank statement.",
  },
  missing: {
    label: "Missing",
    tone: "attn",
    icon: SearchX,
    help: "Present on one side only — e.g. a bank charge never booked in the ledger.",
  },
  timing: {
    label: "Timing",
    tone: "warn",
    icon: Clock,
    help: "Recorded in different periods on each side, e.g. a cheque issued on 30 Sep that clears in October.",
  },
  potential_fraud: {
    label: "Potential fraud",
    tone: "crit",
    icon: AlertOctagon,
    help: "Pattern consistent with fraud or control circumvention. Always requires human review.",
  },
  unknown: {
    label: "Unknown",
    tone: "neutral",
    icon: HelpCircle,
    help: "The agent could not classify this item with enough confidence.",
  },
};

export const CATEGORIES = Object.keys(CATEGORY_META) as Category[];

export function CategoryBadge({ category, className }: { category: Category; className?: string }) {
  const m = CATEGORY_META[category];
  const Icon = m.icon;
  return (
    <Tip content={m.help}>
      <Badge tone={m.tone} className={className} tabIndex={0}>
        <Icon aria-hidden />
        {m.label}
      </Badge>
    </Tip>
  );
}

/* ---------------- StatusBadge ---------------- */
type AnyStatus = FindingStatus | RunStatus | "proposed" | "archived" | "auto" | "manual";

const STATUS_META: Record<AnyStatus, { label: string; tone: BadgeTone; icon: typeof Copy; spin?: boolean }> = {
  open: { label: "Open", tone: "attn", icon: CircleDashed },
  auto_resolved: { label: "Auto-resolved", tone: "sys", icon: CheckCircle2 },
  in_review: { label: "In review", tone: "warn", icon: Eye },
  approved: { label: "Approved", tone: "ok", icon: CheckCircle2 },
  rejected: { label: "Rejected", tone: "crit", icon: XCircle },
  escalated: { label: "Escalated", tone: "crit", icon: ArrowUpRight },
  queued: { label: "Queued", tone: "neutral", icon: Clock },
  running: { label: "Running", tone: "sys", icon: Loader2, spin: true },
  awaiting_review: { label: "Awaiting review", tone: "warn", icon: Eye },
  completed: { label: "Completed", tone: "ok", icon: CheckCircle2 },
  failed: { label: "Failed", tone: "crit", icon: Ban },
  proposed: { label: "Proposed", tone: "ai", icon: Sparkles },
  archived: { label: "Archived", tone: "neutral", icon: Archive },
  auto: { label: "Auto", tone: "sys", icon: CheckCircle2 },
  manual: { label: "Manual", tone: "ok", icon: CheckCircle2 },
};

export function StatusBadge({ status, className }: { status: AnyStatus; className?: string }) {
  const m = STATUS_META[status] ?? { label: status, tone: "neutral" as BadgeTone, icon: FileQuestion };
  const Icon = m.icon;
  return (
    <Badge tone={m.tone} className={className}>
      <Icon aria-hidden className={cn(m.spin && "animate-spin")} />
      {m.label}
    </Badge>
  );
}

export const FINDING_STATUSES: FindingStatus[] = ["open", "in_review", "escalated", "auto_resolved", "approved", "rejected"];
export const findingStatusLabel = (s: FindingStatus) => STATUS_META[s].label;
